<?php

namespace AppBundle\Repository;

/**
 * ChatGroupRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
