<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;

class MessageRepository extends EntityRepository
{
    public function findGroupLastMessageSend($user)
    {

        $qb = $this->createQueryBuilder('m');

        $qb->where('m.user = :user')
            ->setParameter('user',$user)
            ->orderBy('m.dateCreated','DESC');

        return $qb->getQuery()->getResult();
    }

}
