<?php

namespace AppBundle\Repository;
use AppBundle\Entity\ChatGroup;
use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAlltest()
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->add('select','p')
            ->add('from','Post p')
            ->getFirstResult();

    }

    public function findNotInThisGroup(ChatGroup $group)
    {

        $qb = $this->createQueryBuilder('u');
        $qb
            ->join('u.chatGroups','c')
            ->where('c != :group')
            ->setParameter('group',$group);
        return $qb->getQuery()->getResult();
    }
}
