<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAlltest()
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->add('select','p')
            ->add('from','Post p')
            ->getFirstResult();

    }
}
