services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    redirect_register_user.registration.completed:
        class: UserBundle\EventListener\RegistrationConfirmListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }
